client/package-lock.json
client/package.json
client/src/App.tsx
client/src/index.tsx

- Agregue algunos paquetes como react-router-dom y @types/react-redux
- Agregue BrowserRouter

client/* add_packages

---

README.md
api/package-lock.json
client/package-lock.json

Este es un mensaje en prueba del Pull request, se modifica la ultima linea del "Reame" inicial.

mensaje  de prueba

---

api/src/models/User.ts

Made changes at the original version to make it looks like in the ERD

feat(api/src/models):create_model_user

---

api/src/db.ts
api/src/models/User.ts
api/src/models/UserType.ts

Agregué un nuevo modelo: UserType

Feat(api/src/models) create model user type

---

api/src/db.ts
api/src/models/User.ts
api/src/models/UserType.ts

I made the relationships between both tables which creates the intermediate table Users_UserTypes

Feat(api/src/models) link tables users user types

---

api/src/db.ts
api/src/models/Patient.ts

I made the relationship between patients and users

Feat(api/src/models)

---

client/src/actions/index.ts
client/src/components/LoginPage/CreatePage.tsx
client/src/components/LoginPage/LoginPage.tsx

- Creacion de Componentes LoginPage - RegisterPage
- Creacion de la carpeta de styles

feat:(client/components created_components, created_folder_styles)

---

api/src/routes/index.ts
api/src/routes/login.ts
api/src/routes/register.ts

adds login and register routes interaction with the DB

Feat api routes register

---

api/src/db.ts
api/src/models/Appointment.ts
api/src/models/User.ts

I setted up the active and isStaff columns with a default value. Also remove "<User>". Joaquin: it seems to work out without it.

Fix(api/src/models)

---

api/src/db.ts
api/src/models/Appointment.ts
api/src/models/Patient.ts
api/src/models/Plan.ts
api/src/models/User.ts
api/src/models/UserType.ts

It seems to be causing problems while trying to insert a new record into the data base

Remove model name at export class

---

api/src/db.ts
api/src/models/Appointment.ts
api/src/models/AppointmentDetail.ts
api/src/models/Patient.ts
api/src/models/Plan.ts
api/src/models/User.ts
api/src/models/UserType.ts

I added the new model and also did some relationships

feat(api/src/models):add_AppointmentDetails_model

---

api/src/routes/login.ts

now the refresh token is stored in the DB

adds refreshToken interaction with the DB

---

api/src/routes/login.ts
api/src/routes/register.ts

send the refreshTokens in httpOnly cookies.
remove unnecessary values in Users create

Feat refresh token cookies

---

README.md
api/lib/config.ts
api/src/routes/login.ts
api/src/routes/register.ts
client/src/components/Login/Login.tsx
client/src/components/Register/Register.tsx

Fix CORS configurtion, adds login/register logic, and minor fixing

Frontend loggin

---

api/src/assets/populate.ts

now the fn wont duplicate the table rows when force is set false

fix-api-populate-fn

---

client/src/actions/index.ts
client/src/actions/types.ts
client/src/components/Home/Home.tsx
client/src/components/Home/UserHome/UserHome.module.css
client/src/components/Home/UserHome/UserHome.tsx
client/src/reducers/index.ts

add appointments from the back,
improvements in the css,
add actions getUserInfo and getAppointments,
add actionType in reducer

add appointments from the back and improvements in the css

---

api/src/routes/index.ts
api/src/routes/login.ts
api/src/routes/register.ts
api/src/routes/updateUser.ts

Add change password, modify patients info and fix refreshToken bug

Feat change personal info

---

api/src/assets/populate.ts
api/src/routes/specialities.ts
client/package-lock.json
client/src/App.tsx
client/src/actions/index.ts
client/src/actions/types.ts
client/src/components/Home/Appointments/Appointments.module.css
client/src/components/Home/Appointments/Appointments.tsx
client/src/components/Home/Appointments/NewAppointment.module.css
client/src/components/Home/Appointments/NewAppointment.tsx
client/src/components/Home/Nav/Nav.tsx
client/src/components/Home/UserHome/UserHome.tsx
client/src/reducers/index.ts

Agregue la mitad de los appointments. Falta generar los nuevos

Feat client/components/home/appointments

---

api/package.json
api/src/routes/index.ts
api/src/routes/mercadopago.ts

1. new module added
2. route added to index
3. route mercadopago created

mercadopago-route-added

---

client/src/components/Landing/Features.module.css
client/src/components/Landing/Features.tsx
client/src/components/Landing/Main.tsx
client/src/components/Landing/Us.module.css
client/src/components/Landing/Us.tsx

1. Added new descriptive texts
2. Reduced height of bottom div (it got too large)
3. Remove some paragraphs
4. Changed margin on some paragraphs

text changes and css corrections

---

api/src/models/Patient.ts
client/src/components/Landing/Features.module.css
client/src/components/Landing/Features.tsx
client/src/components/Landing/Main.tsx
client/src/components/Landing/Us.module.css
client/src/components/Landing/Us.tsx

Me aparece un commit anterior, como le sucedía a Luis. No sé por qué pasa pero no generará ninguno problema a priori

Fix patient model

---

api/src/routes/appointmentDetails.ts
api/src/routes/appointments.ts
api/src/routes/index.ts

1) add post AppointmentDetails route
2) include AppointmentDetails at get appointment by patientId route.

feat add appointmentDetails route

---

client/src/App.tsx
client/src/components/History/History.tsx
client/src/components/Home/Nav/Nav.tsx
client/src/styles/History/History.css

- Agregando componente History de Pacientes
- Agregando ruta en el App.tsx
- Agregando (provisionalmente) en el componente Nav el Link dirigido a History

(feat:client/components) added_component_history_patients

---

client/src/components/History/History.tsx
client/src/styles/History/History.css

- Adaptando el diseño del componente History

(fix:client/component/history) adapting_design_history_component

---

api/src/routes/appointments.ts
api/src/routes/mercadopago.ts
client/src/actions/index.ts
client/src/components/Home/Home.tsx

add update appointment endpoint
modify mercadopago endpoint
adds functionality to Home to register payment in appointment

Feat after payment

---

client/src/components/Home/Appointments/Appointments.module.css
client/src/components/Home/Appointments/Appointments.tsx
client/src/components/Home/Appointments/NewAppointment.tsx

- Agregando modulo de Header a componentes Appointments y NewAppointment
- Arreglos de diseño

(fix:client/Appointments) fix_design_component_Appointment

---

api/src/routes/login.ts
client/src/App.tsx
client/src/actions/index.ts
client/src/actions/interfaces.ts
client/src/actions/types.ts
client/src/components/History/History.tsx
client/src/components/Home/Appointments/Appointments.tsx
client/src/components/Home/Appointments/Card.tsx
client/src/components/Home/Appointments/CardSpec.tsx
client/src/components/Home/Appointments/NewAppointment.tsx
client/src/components/Home/Home.tsx
client/src/components/Home/UserHome/UserHome.tsx
client/src/components/Login/Login.tsx
client/src/components/UserProfile/EditDataProfile/EditDataPofile.tsx
client/src/components/UserProfile/UserProfile.tsx
client/src/reducers/index.ts

Se me hizo un poco grande, perdon.

Fix use effects

---

api/src/routes/login.ts
client/src/components/Login/Login.tsx

- Cambiando en api/Login el texto de español a ingles, del retorno en texto de error al loguearse.
- Agregando al componente Login el texto error del back

(fix:client/Login) added_error_userOrpsswd_doesnt_exists

---

api/index.ts
api/src/assets/Lists/plansList.ts
api/src/assets/defaultPlans.ts
api/src/routes/users.ts
client/src/actions/index.ts
client/src/actions/types.ts
client/src/components/Register/Register.tsx
client/src/reducers/index.ts

- Added array of plans
- Added fn which loads the plans into db
- Added action to get plans from db
- Modified Register.tsx to send planId when a new user creation happens

fix/add: plans preloaded. now plans from register work

---

client/src/components/Home/Appointments/Appointments.tsx
client/src/components/Home/Appointments/NewAppointment.tsx
client/src/components/Landing/Main.tsx
client/src/components/Login/Login.tsx
client/src/components/MercadoPago/MercadoPago.tsx
client/src/components/Register/Register.tsx
client/src/reducers/index.ts

- fixed bug in reducer logout
- dispatch to get list of plans
- now we calculate the price based on the coverage percentage (0%, 25%, 50%, 90%)
- fix some memory leaks on Login.tsx

Fixes: Mercado Pago now gets the price according to plan and other fixes

---

client/src/App.tsx
client/src/actions/index.ts

fix admin page route
fix actions

Fix last merge

---

client/src/components/History/History.tsx

- Arreglando el iterador en History

(fix:client/History) fixed_History

---

api/src/assets/defaultMedicalStaff.ts
api/src/routes/users.ts
client/src/components/UserProfile/DataProfile/DataProfile.module.css
client/src/components/UserProfile/DataProfile/DataProfile.tsx
client/src/components/UserProfile/EditDataProfile/EditDataPofile.tsx

Now plan info is obtained from patientInfo and display correctly

hotfix on profile info

---

README.md
client/src/components/Home/Appointments/Appointments.tsx
client/src/components/Home/Coverage/Coverage.module.css
client/src/components/Home/Coverage/Coverage.tsx
client/src/components/Home/Nav/Nav.tsx
client/src/components/Landing/Main.tsx
client/src/components/MercadoPago/MercadoPago.module.css
client/src/components/UserProfile/DataProfile/DataProfile.tsx

- fixed problem with plans in several places.
- Added coverage modal

fix on plans and coverage added

---

api/lib/storage.ts
api/src/routes/studies.ts

The files now will be storage at client/public/storage (we need to create this folder)

change post/put and storage folder placement

---

client/src/components/Admin/Admin.module.css
client/src/components/Admin/Admin.tsx
client/src/components/Admin/Appointments/AddAppointment.module.css
client/src/components/Admin/Appointments/AddAppointment.tsx
client/src/components/Admin/Appointments/Appointments.module.css
client/src/components/Admin/Appointments/Appointments.tsx
client/src/components/Admin/Appointments/AppointmentsDetail.module.css
client/src/components/Admin/Appointments/AppointmentsDetail.tsx
client/src/components/Admin/Medics/AddMedic.module.css
client/src/components/Admin/Medics/AddMedic.tsx
client/src/components/Admin/Medics/Medics.module.css
client/src/components/Admin/Medics/Medics.tsx
client/src/components/Admin/Medics/MedicsDetail.module.css
client/src/components/Admin/Medics/MedicsDetail.tsx
client/src/components/Admin/Patients/AddPatient.module.css
client/src/components/Admin/Patients/AddPatient.tsx
client/src/components/Admin/Patients/Patients.module.css
client/src/components/Admin/Patients/Patients.tsx
client/src/components/Admin/Patients/PatientsDetail.module.css
client/src/components/Admin/Patients/PatientsDetail.tsx

Agregue todo CSS al admin panel y modifique algunas cosillas

Modified CSS and some proporties of admin panel

---

client/src/components/History/History.tsx
client/src/styles/History/History.css

- Agregando funcionalidad para subir y bajar archivos en el componente History

(fix:client/History) added_button_uploadFiles

---

client/src/App.tsx
client/src/actions/index.ts
client/src/actions/types.ts
client/src/components/Medic/MedicAppointments/MedicAppointmentDetail.module.css
client/src/components/Medic/MedicAppointments/MedicAppointmentDetail.tsx
client/src/components/Medic/MedicAppointments/NewStudie.module.css
client/src/components/Medic/MedicAppointments/NewStudie.tsx
client/src/reducers/index.ts

Agregue el form para agregar un nuevo study, falta un poco de CSS

Added New Study form

---

api/src/routes/login.ts
api/src/routes/patients.ts
api/src/routes/updateUser.ts
client/src/components/Admin/Patients/PatientsDetail.tsx
client/src/components/Admin/requests.tsx

adds revoke user and make user admin

Change permissions

---

client/src/components/Home/UserHome/UserHome.module.css
client/src/components/Home/UserHome/UserHome.tsx
client/src/components/Medic/MedicProfile/EditDataProfile/ChangePass/ChangePass.tsx
client/src/components/Medic/MedicProfile/EditDataProfile/EditDataPofile.tsx
client/src/components/Medic/MedicProfile/EditDataProfile/EditDataProfile.module.css
client/src/components/Medic/MedicProfile/MedicProfile.module.css
client/src/components/MercadoPago/MercadoPago.module.css
client/src/components/UserProfile/EditDataProfile/EditDataPofile.tsx
client/src/components/UserProfile/EditDataProfile/EditDataProfile.module.css

css improviments and controlled form

---

api/lib/storage.ts
api/src/assets/addDays.ts
client/src/assets/addDays.ts

Refactor addDays function without using toLocaleDate

Updates fixes and more

---

client/src/components/History/History.tsx
client/src/styles/History/History.css

- Arreglando el componente History

(fix:client/History) fixed_component_History_patient

---

api/lib/config.ts
api/src/routes/appointmentsAvb.ts
api/src/routes/index.ts
api/src/routes/login.ts

- fix on appointmentavb to deploy
- remove out of date routes
- change token duration from 10min to 60min

fixes: minor changes on api

---

client/src/components/Medic/MedicAppointments/MedicAppointmentDetail.module.css
client/src/components/Medic/MedicAppointments/MedicAppointmentDetail.tsx
client/src/components/Medic/MedicAppointments/NewReviewAppointment.module.css
client/src/components/Medic/MedicAppointments/NewReviewAppointment.tsx
client/src/components/Medic/MedicPatientHistory/MedicPatientHistory.module.css
client/src/components/Medic/MedicPatientHistory/MedicPatientHistory.tsx
client/src/styles/Medic/MedicPatientHistory/MedicPatientHistory.css

Modifique el historial del paciente en CSS para que quede igual a los otros y arregle mini bugs del front

Modified Patient History

---

client/src/App.tsx
client/src/actions/index.ts
client/src/components/Admin/requests.tsx
client/src/components/History/History.tsx
client/src/components/Home/Appointments/Appointments.tsx
client/src/components/Home/Appointments/AppointmentsDetail.tsx
client/src/components/Home/Appointments/Card.tsx
client/src/components/Home/Appointments/CardSpec.tsx
client/src/components/Login/Login.tsx
client/src/components/Medic/MedicAppointments/NewStudie.tsx
client/src/components/Register/Register.tsx

- var called URL_DEPLOY created at actions/index with the url of the deployed server on heroku

url for deploy added

---

client/src/components/Medic/MedicHome/MedicHome.module.css

- Pensaba hacer mas cambios pero si vamos a hacerla responsive es mejor hacer esos cambios ahí

medic home appointments center

---

client/src/styles/LoginPage/Login.css

- Arreglando el checkbox en el Login

(fix:client/Login) fixDesign_check_component_Login

---

client/src/components/History/History.module.css
client/src/components/History/History.tsx
client/src/components/Home/Appointments/AppointmentsDetail.module.css
client/src/components/Home/Appointments/AppointmentsDetail.tsx
client/src/components/Medic/MedicAppointments/NewReviewAppointment.tsx
client/src/reducers/index.ts

Edite cosas del Historial de estudios de paciente y deje el Appoiment detail del paciente como el del medico

Fixed History and Appoiment Detail as Pacient

---

client/src/components/Home/UserHome/UserHome.module.css
client/src/components/Home/UserHome/UserHome.tsx
client/src/components/Medic/MedicPatientHistory/MedicPatientHistory.module.css
client/src/components/Medic/MedicPatientHistory/MedicPatientHistory.tsx

- Agregando boton en el Home del perfil de Paciente dirigiendose a Studies

(fix:client/UserHome) direction_buton_to_PatientStudies
